Repository ZCG-coder/Steppable, pull requests merged in 2024-05, with the labels that each got.

#12 Add build.py for easier cross-platform building.
  .gitignore
  include/util.hpp
  src/CMakeLists.txt
  src/util.cpp
  tools/__init__.py
  tools/build.py
  tools/building/compiler_detection.py
  tools/building/directories.py
  tools/building/paths.py
  tools/building/printing.py
  tools/building/project.py
  tools/new_component.py
Labels: feature, python

#17 Update README.md
  README.md
Labels: documentation

#18 Fixed multiply (#16)
  .gitignore
  .idea/editor.xml
  .idea/misc.xml
  src/multiply/multiplyReport.cpp
  src/power/power.cpp
  src/power/powerReport.cpp
  tests/testPower.cpp
Labels: bug

#19 Fixed multiply (#16)
  .gitignore
  .idea/editor.xml
  .idea/misc.xml
  src/multiply/multiplyReport.cpp
  src/power/power.cpp
  src/power/powerReport.cpp
  tests/testPower.cpp
Labels: bug

#20 Add a root component to take n-th roots.
  CMakeLists.txt
  include/fn/basicArithm.hpp
  src/CMakeLists.txt
  src/division/division.cpp
  src/root/root.cpp
  src/root/rootReport.cpp
  src/root/rootReport.hpp
  src/util.cpp
  tests/CMakeLists.txt
  tests/testRoot.cpp
  tools/building/project.py
Labels: feature

#21 Add a new function `moveDecimalPlaces` to rounding.hpp.
  Steppable.sublime-project
  include/rounding.hpp
  include/util.hpp
  src/multiply/multiply.cpp
  src/multiply/multiplyReport.cpp
  src/multiply/multiplyReport.hpp
  src/root/root.cpp
  src/rounding.cpp
  src/util.cpp
Labels: T-Feature, C-C++, W-Incompatible

#27 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: T-Documentation
